global:
  tolerations:
    - key: "critical-components"
      operator: "Equal"
      value: "critical"
      effect: "NoSchedule"
longhornUI:
  replicas: 1
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
csi:
  # -- Replica count of the CSI Attacher
  attacherReplicaCount: 1
  # -- Replica count of the CSI Provisioner
  provisionerReplicaCount: 1
  # -- Replica count of the CSI Resizer
  resizerReplicaCount: 1
  # -- Replica count of the CSI Snapshotter
  snapshotterReplicaCount: 1

persistence:
  # -- replica of PV -- as homelab, we can set it to 1
    defaultClassReplicaCount: 1

defaultSettings:
  deletingConfirmationFlag: true

#################################
#### Longhorn Uninstall Job #####
#################################
uninstallJob:
  enabled: false

#################################
##### Longhorn UI Service #######
#################################
service:
  ui:
    type: LoadBalancer

#################################
#### Longhorn Customizations ####
##################################
customizations:
  taintTolerationSetting:
    enabled: true