grafana: 
  service:
    type: LoadBalancer
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
alloy: 
  alloy:
    configMap:
      create: true
      content: |
        {{ .Files.Get "alloy-config.hcl" | nindent 6 }}
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  serviceMonitor:
    enabled: false
