apiVersion: v2
name: grafana-stack
description: A custom Grafana stack with Grafana, Grafana Alloy
type: application
version: 0.1.0
appVersion: "1.10.0"
dependencies:
  - name: grafana
    version: 9.3.0
    repository: "file://./dependencies/grafana"
  - name: alloy
    alias: grafana-alloy
    version: 1.2.0
    repository: "file://./dependencies/alloy"
