apiVersion: v2
appVersion: v1.16.0
description: A Helm chart for cert-manager
home: https://cert-manager.io
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
- cert-manager
- kube-lego
- letsencrypt
- tls
dependencies:
  - name: cert-manager
    version: 1.16.0
    repository: "file://./dependencies/cert-manager"

name: cert-manager
version: 1.0.0
