#################################
### Prometheus CRDs ############
#################################

prometheus-crds:
  alertmanagerconfigs:
    ## enabled defines if the CRD should be installed
    enabled: false

  ## alertmanagers configures the AlertManager CRD
  alertmanagers:
    ## enabled defines if the CRD should be installed
    enabled: false

  ## podmonitors configures the PodMonitor CRD
  podmonitors:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## probes configures the Probe CRD
  probes:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## prometheusagents configures the PrometheusAgent CRD
  prometheusagents:
    ## enabled defines if the CRD should be installed
    enabled: false

  ## prometheuses configures the Prometheus CRD
  prometheuses:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## prometheusrules configures the PrometheusRule CRD
  prometheusrules:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## scrapeconfigs configures the ScrapeConfig CRD
  scrapeconfigs:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## servicemonitors configures the ServiceMonitor CRD
  servicemonitors:
    ## enabled defines if the CRD should be installed
    enabled: true

  ## thanosrulers configures the ThanosRuler CRD
  thanosrulers:
    ## enabled defines if the CRD should be installed
    enabled: false

##################################
### Prometheus Node Exporter #####
##################################
node-exporter:
  tolerations:
  - key: "critical-components"
    operator: "Equal"
    value: "critical"
    effect: "NoSchedule"
  prometheus:
    monitor:
      enabled: true


####################################
######## kube-state-metrics ########
####################################
state-metrics:
  tolerations:
  - key: "critical-components"
    operator: "Equal"
    value: "critical"
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  prometheus:
    monitor:
      enabled: true
